service:
  name: auction-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  environment: 
    AUCTIONS_TABLE_NAME: ${self:custom.AuctionsTable.name}
  iamRoleStatements:
    - ${file(iam/AuctionsTableIAM.yml):AuctionsTableIAM}

resources:
  Resources:
    AuctionsTable: ${file(resources/AuctionsTable.yml):AuctionsTable}



functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction
          #authorizer: arn:aws:lambda:us-east-1:334767101463:function:auth-service-dev-auth:2

  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: get
          path: /auctions
          #authorizer: ${self:custom.authorizer}

  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: get
          path: /auction/{id}
          #authorizer: ${self:custom.authorizer}

  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: patch
          path: /auction/{id}/bid
          #authorizer: ${self:custom.authorizer}
      
  processAuction:
    handler: src/handlers/processAuctions.handler
    events:
      - schedule: rate(1 minute)



custom:
  authorizer: arn:aws:lambda:us-east-1:334767101463:function:auth-service-dev-auth:2
  AuctionsTable: 
    name: !Ref AuctionsTable
    arn: !GetAtt AuctionsTable.Arn
